fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Eeckman\UserBundle\Entity\User
    registration:
        form:
            type: eeckman_user_registration
            validation_groups: [EeckmanRegistration]
    profile:
        form:
            type: eeckman_user_profile
            validation_groups: [EeckmanProfile]