#services:
##    eeckman_user.example:
##        class: Eeckman\UserBundle\Example
##        arguments: [@service_id, "plain_value", %parameter%]
#      eeckman_user.my_provider:
#          class: Eeckman\UserBundle\Security\Provider\MyProvider
#          public: false
#          arguments : ["@fos_user.user_manager"]