<?php

namespace Eeckman\TransportsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarriersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarriersRepository extends EntityRepository
{
}
