<?php

namespace Eeckman\TransportsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightsRepository extends EntityRepository
{
}
