<?php

namespace Eeckman\TransportsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PackagingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackagingsRepository extends EntityRepository
{
}
