<?php

namespace Eeckman\TransportsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportsRepository extends EntityRepository
{
}
