<?php

namespace Eeckman\TransportsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Transports_TransportTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Transports_TransportTypesRepository extends EntityRepository
{
}
