<?php

namespace Eeckman\PolicyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GuaranteesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuaranteesRepository extends EntityRepository
{
}
