<?php

namespace Eeckman\PolicyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PolicyHoldersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyHoldersRepository extends EntityRepository
{
}
