<?php

namespace Eeckman\PolicyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PolicyHoldersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyHoldersRepository extends EntityRepository
{
    public function findByContactID($IDContact)
    {
        return $this->createQueryBuilder('e')
            ->where('e.iDContact = :contactID')
            ->setParameter('contactID', $IDContact)
            ->getQuery()
            ->getResult();
    }
}
