<?php

namespace Eeckman\CoverageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoveragesExtensionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoveragesExtensionsRepository extends EntityRepository
{
}
