<?php

namespace Eeckman\CoverageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoveragesTransportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoveragesTransportsRepository extends EntityRepository
{
}
