<?php

namespace Eeckman\EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventExtensionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventExtensionsRepository extends EntityRepository
{
    public function findByEventID($IDEvent)
    {
        return $this->createQueryBuilder('e')
            ->where('e.iDEvent = :eventID')
            ->setParameter('eventID', $IDEvent)
            ->getQuery()
            ->getResult();
    }
}
