<?php

namespace Eeckman\EventsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventExtensionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventExtensionsRepository extends EntityRepository
{
}
