<?php

namespace Eeckman\CertificateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CertificatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatesRepository extends EntityRepository
{
}
