<?php

namespace Eeckman\CertificateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CertificateTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificateTypesRepository extends EntityRepository
{
}
