<?php

namespace Eeckman\ObjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LengthUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LengthUnitRepository extends EntityRepository
{
}
