<?php

namespace Eeckman\ObjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Object_TypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Object_TypesRepository extends EntityRepository
{
}
