<?php

namespace Eeckman\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompaniesTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompaniesTypesRepository extends EntityRepository
{
}
